### PR TITLE
Anime slash command

### PR DESCRIPTION
**Pull request by ocgineer**
Been a long time since I've attempted a pull request or coded in general but here goes.

I have added support for /anime command for Sonarr, which adds the selected 'series' as type anime, instead of standard. In addition, the add_series() and add_movies() can now accept a list of tags, instead of a single tag, the settings file will have two options for anime tagging as an example.

### CODE REVIEW

**Comment by toddrob99** [comment]
Thanks for the contribution. I am going to include this in v2, along with some other enhancements. I assume you are already running a custom docker image with your changes included, but I will be publishing v2 to `toddrob/searcharr:beta` on docker hub until it's ready for general release. Keep in mind I will be pushing other features to that tag as well, and there may be bugs.

**Comment by toddrob99** [comment]
Wait... Is the only difference between anime and standard series the `anime` tag that's being added (if the option is enabled)? Is there any way to identify a series as anime programmatically so the user doesn't have to issue a different command for anime just to add that tag? Can you give me some examples of anime series so I can review the data? There might be an anime genre on them that can be used to determine when to add the tag.

I merged this PR to the `v2` branch, but now that I see there is very little difference between the functionality for `/series` and `/anime`, I am going to work on a more efficient way to get the `anime` tag in there. One of the features I am considering is to allow adding of arbitrary tags when adding a series/movie, so even if I can't figure out a way to automatically add the `anime` tag, it should not be any more effort for the user to add the `anime` tag themselves than it would be for them to use a different command.

**Comment by ocgineer** [comment]
The tags was optional, it was more that the series was added as a type of anime but yes I made this change for me to use in a custom docker as I only use sonarr for Anime so I wanted to make sure the type was set correctly. :)

**Comment by toddrob99** [comment]
Oh I see, there is a seriesType param in the Sonarr add series API call too. Okay, let me think about this some more but I think there will be a more efficient way than adding a separate command. 

Maybe I'll add a setting to enable the different series types (standard, anime, daily), and if more than one is enabled, present the user with a set of buttons to choose which type to add. If only one is enabled, use that type (so you would enable only anime and not have to select it each time, since that's the only series type you use).

I am also planning to support custom commands, so you would be able to use `/anime` if you want.

**Comment by toddrob99** [comment]
I have been trying to think of a good way to automatically detect anime series and add them to Sonarr with the anime series type, but it seems like some anime series should actually be added to Sonarr with the standard series type. For example, My Hero Academia appears to have its episodes grouped into multiple seasons (standard series type). 

I see "Anime" in the genre list, so I am thinking of prompting the user to select a series type when the Anime genre is detected. 

I have already implemented custom command aliases for the beta branch (not yet published as a docker image), so you could configure Searcharr to use `/anime <title>` and it would prompt each time to add as standard or anime series type.

Do you think that is a good solution?

**Comment by ocgineer** [comment]
A prompt is okay, as I think automating could have some issues if the metadata providers have incorrect data regarding anime as well. For the Anime shows I've added I've only used type anime and haven't really found issues, I know that TMDB sometimes has weird groupings on long running shows (such as My Hero Academia or Hunter x Hunter (2014)) but for normal seasonal anime it works so far perfectly.

**Comment by toddrob99** [comment]
I just pushed a beta build to docker hub under `toddrob/searcharr:beta`. I have not written up release notes yet, but it adds a few new settings, including one that will allow you to customize the /series command to /anime if you want.

```
sonarr_series_command_aliases = ["series"]  # e.g. ["series", "tv", "t"]
radarr_min_availability = "released"  # options: "announced", "inCinemas", "released"
radarr_movie_command_aliases = ["movie"]  # e.g. ["movie", "mv", "m"]
```

When a series is presented with "Anime" in the list of genres, an extra button will appear at the bottom of the inline keyboard to "Add Series as Anime Type!".

If you get a chance, try it out and let me know if you think the flow is straightforward enough.

**Pull request merged**
